name: rigoo_marine
description: Your nÂ°1 Boating Companion
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.10.7 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cloudinary_public: ^0.21.0
  # State Management
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  
  # Navigation
  go_router: ^17.0.1
  
  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^7.1.0
  smooth_page_indicator: ^2.0.1
  cached_network_image: ^3.3.1
  
  # Forms & Validation
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  
  # Utilities
  freezed_annotation: ^3.1.0
  json_annotation: 4.9.0
  equatable: ^2.0.5
  intl: ^0.20.2
  uuid: ^4.3.3
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  cloud_functions: ^4.6.0
  image_picker: ^1.0.7
  shared_preferences: ^2.5.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^4.0.0+1
  freezed: ^3.2.3
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/